version: "3.9"
services:
  framepy:
    build: .
    image: framepy:0.1.0
    volumes:
      - ./frameData:/frameData
      - ./frame.py:/usr/bin/frame.py
    devices:
      - /dev/fb0:/dev/fb0
    # Set to running user. Copy .env-example to .env to use default pi user.
    user: "${USER}"
    entrypoint: frame.py -f /frameData/dropbox_uploader.config --baseDir /frameData
    tty: true
    stdin_open: true

  setup:
    build: .
    image: framepy:0.1.0
    volumes:
      - ./frameData:/frameData
      - ./frame.py:/usr/bin/frame.py
    command: dropbox_uploader.sh -f /frameData/dropbox_uploader.config
    user: "${USER}"
    tty: true
    stdin_open: true
